### ISSUE TITLE
Fix SDKs

### ISSUE THREAD

**Issue by eobie3** [Captianrock/android_PV#104]
Unable to locate SDK folder on PCs - likely because of the direction of the slashes

**Comment by mlinarev** [comment]
Are you using hardcoded slashes or are you using File.pathSeparator?

**Comment by eobie3** [comment]
Hardcoded - I'll try with the separator. Didn't realize that existed, thank you

**Comment by eobie3** [comment]
ed04c4548e040658f51d4d9b6d6725f9a9e67767
