### ISSUE TITLE
Decompiling APK in Java client

### ISSUE THREAD

**Issue by mlinarev** [Captianrock/android_PV#24]
As a user of the Java client, I would like to upload an APK instead of the source code. The APK should be decompiled into Java automatically. If the decompilation process is not successful, the Java client should ask for the source code of the app under analysis.

**Comment by beblount** [comment]
I'm having issues figuring out how to use the dex2jar api to convert the Dex files. The only method of using the tool seems to be through the command line. Any advice?

**Comment by mlinarev** [comment]
Command line sounds good to me. In Java you can invoke commands as described here:

http://www.mkyong.com/java/how-to-execute-shell-command-from-java/
http://stackoverflow.com/questions/4157303/how-to-execute-cmd-commands-via-java

**Comment by beblount** [comment]
https://github.com/Captianrock/android_PV/commit/2163ee66f7d7cca516ee0d74be509d3667c635b2
