### ISSUE TITLE
Automatic deploy of APK and "xposed" module

### ISSUE THREAD

**Issue by mlinarev** [Captianrock/android_PV#26]
As a user of the Java client, I would like to have an option to automatically deploy both APK of the app under analysis and "xposed module" into a device connected to the computer running the Java client

**Comment by eobie3** [comment]
Able to deploy an Xposed module via command line. Need to run it through Java after getting the module apk created

**Comment by eobie3** [comment]
Automatically deployed

f36e0bc5731d9e0421dd95a075f69b47fe793640
