### ISSUE TITLE
Parsing of execution logs

### ISSUE THREAD

**Issue by mlinarev** [Captianrock/android_PV#28]
As a user of the web client, I would like to upload several execution logs and parse the logs to be persisted locally in a database.

**Comment by Captianrock** [comment]
-Just a update on my progress so far.

Went through researching databases and learning the ropes of how to implement them. 
I wanted to go for Parse, however after a few hours it was revealed to me that it was shutdown by Facebook.

Thinking about using a MySQL server that can communicate with the Android phone, hopefully through RESTFUL. A lot of unfamiliar technologies to get used to but will keep posted.

**Comment by mlinarev** [comment]
MySQL is OK. You do not need a DB engine with RESTUL capabilities. For this sprint, the files are uploaded (via a web form) to the web client.

**Comment by Captianrock** [comment]
Another update!

-Database is up and running! But still needs some tweaking so not gonna close this issue quite yet!
As of now,

Preconditions: The logcats are saved with the Xposed tag set.
- The data file is in the same directory as the java application.

-As a user, I am able to upload an execution log saved as a text file and parse the logs to be persisted in the database in a multiset format. 

What I will be finish before end of spring break: Create relations without null values. (As of now it gets confused with the methodStart and methodEnd disjointness).
A web client will need to be set up. Not quite sure who is in charge of that. Am I involved in that as well?

**Comment by mlinarev** [comment]
The sub team working on issues related to the web client should set up/develop the web client.

**Comment by Captianrock** [comment]
a39b5af1690ec4819172a42ba2e4cfc0b2f090ca

**Comment by Captianrock** [comment]
-Fixed bug of not considering when database is already populated. 
-Merged to Branch, yet having problems with masters

**Comment by Captianrock** [comment]
Final Update. 

Everything is working fine in masters. 
Is it ok if I close this issue for now?, since a user is able to take in a file and it is probably parsed, and preserved within a database. The issue remaining is whether the database lies within the web client or not.
