### ISSUE TITLE
Flame graphs

### ISSUE THREAD

**Issue by mlinarev** [Captianrock/android_PV#29]
As a user of the web client, I would like to visualize the execution logs using flame graphs.

**Comment by Captianrock** [comment]
Question, do these flame graphs need to go through a webapp or is this something you download and use?

**Comment by mlinarev** [comment]
What do you mean? BTW, who is the owner of the flame graphs task?

**Comment by Quansword** [comment]
I am, and I believe that they should go through the webapp. At least, that was what you seemed to say in our original sprint meeting.

**Comment by Quansword** [comment]
Progress:

I mostly understand how flame graphs work now, and I know how to make them. I need a stack trace to make one for our program though, which I don't believe we have yet.

**Comment by mlinarev** [comment]
The log collected with the exposed module should have timestamps for entry and exit time of each method call; so, there is no need for stack trace

**Comment by Quansword** [comment]
My understanding from research is that flame graphs are for the visualization of sampled stack traces, and that the code existing for them requires a stack trace to build a flame graph. 

I don't believe that we can only give the input of timestamps for methods unless the code for making the graph is heavily modified. The code for the graph is written in Perl, however, which I have minimal knowledge of and no experience with.

**Comment by mlinarev** [comment]
With the timestamps you can create "stack traces".

**Comment by Captianrock** [comment]
We decided to make these into Donut Chart to display the same information as a flame graph.
