### ISSUE TITLE
User Authentication

### ISSUE THREAD

**Issue by eobie3** [Captianrock/android_PV#34]
As a user of the web client, I would like to authenticate myself when logging in.

**Comment by Captianrock** [comment]
I am assuming this involves making a website as well?

**Comment by eobie3** [comment]
This includes ensuring that any files I, as a user, upload aren't accessible to anyone else.

**Comment by Captianrock** [comment]
Quickie update on the website! After much deliberation I found that the XAMPP is the best tool for us!

It incorporates a MYSQL database and an Apache webserver locally!

**Comment by Captianrock** [comment]
bbe3ec8e0d624ddab2333e93739f16367c3d5d68

Web Login Page is working correctly when using the MySql connected to XAMPP.
Working on seeing how to connect to a database outside of XAMPP.

**Comment by Captianrock** [comment]
9d1ea70e9c3af8e6006fdead562e320f7d834953

-Just made a datadump file for sql. If that doesn't work I'll just give the data folder file.
-Fixed bugs in the login page and added extra security features like logging out and preventing an unathenticated user from accessing homepage.
- Created a basic webpage template as the homepage with Bootstrap. Still learning how to use all these tools.
