### ISSUE TITLE
High Charts

### ISSUE THREAD

**Issue by eobie3** [Captianrock/android_PV#36]
As a user of the web client, I would like to view the stats as high charts (highcharts.com). I would also like to view the "k" most apps (i.e., most k time consuming methods).

**Comment by Quansword** [comment]
Highcharts are finished. I figured out how to display them on the webapp with a static set of data before sifting through the parse of the logcat and dynamically displaying the data.

e24f2b8fef33c7690543204ac28b67b565757b23

**Comment by Captianrock** [comment]
Fixed the pie charts to avoid duplicates and added the most time consuming method. with the length of time it took. 
b826f1662afce39608f96edb3eb0881da202df33
