### ISSUE TITLE
Xposed Module generates Anonymous Class tags when parsing through APKs

### ISSUE THREAD

**Issue by Captianrock** [Captianrock/android_PV#40]
ThrouWhen generating a Xposed Module through a decomplied APK. It can sometimes cause Anymous Class tags when using a method with the parameters with an object that does not have a name.

**Comment by eobie3** [comment]
Is it safe to assume that there won't be any classes called AnonymousClass#? (Replace # with number). I don't know how I would differentiate it from a true class - the AST parser isn't giving me any useful information.

**Comment by mlinarev** [comment]
No Guarantee because AnonymousClass# is a valid class name. But you can identify whether the AST node is instance of AnonymousClassDeclaration:

http://help.eclipse.org/juno/index.jsp?topic=%2Forg.eclipse.jdt.doc.isv%2Freference%2Fapi%2Forg%2Feclipse%2Fjdt%2Fcore%2Fdom%2FAnonymousClassDeclaration.html

**Comment by eobie3** [comment]
No, unfortunately it's been restructured as a TypeDeclaration. Running node.resolveBinding().getDeclaringClass().isAnonymous(), where node is the MethodDeclaration, returns false. I've checked node.getParent() as well, and the result's type is TypeDeclaration.

**Comment by eobie3** [comment]
The AnonymousClass# are nested classes (as far as I know). Quick example:


   `
    public final class ActivityAlarmSettings extends Activity {
    
    ....

    /* renamed from: com.angrydoughnuts.android.alarmclock.ActivityAlarmSettings.11 */
    class AnonymousClass11 implements OnTimeSetListener {
        final /* synthetic */ AlarmTime val$time;

        AnonymousClass11(AlarmTime alarmTime) {
            this.val$time = alarmTime;
        }

        public void onTimeSet(int hourOfDay, int minute, int second) {
            ActivityAlarmSettings.this.info.setTime(new AlarmTime(hourOfDay, minute, second, this.val$time.getDaysOfWeek()));
            ActivityAlarmSettings.this.settingsAdapter.notifyDataSetChanged();
            ActivityAlarmSettings.this.removeDialog(Dialogs.TIME_PICKER.ordinal());
        }
    }`

**Comment by mlinarev** [comment]
Ok, so you have a visitor for method declarations and then you wanna check whether the method owner (i.e., a class) of the visited method is an anonymous class. 

You could try a double-phase analysis: (i) you have a visitor of AnonymousClassDeclarations, you parse the source code using the AnonymousClassDeclaration visitor to collect a list AC of all the Anonymous classes (list should have qualified names); (ii), you parse again the code but with the method visitor, and with it,  you verify if the qualified name of node.resolveBinding().getDeclaringClass() is in the AC list.

**Comment by eobie3** [comment]
I am running this:

        final CompilationUnit cu = (CompilationUnit) parser.createAST(null);

        cu.accept(new ASTVisitor() {
            Set names = new HashSet();

            public boolean visit(AnonymousClassDeclaration node) {

                System.out.println("found anonymous class");

                return false;
            }

            public boolean visit(MethodDeclaration node) {
                .....
            }

I just added the visit AnonClass block - is that how you were thinking? It never hit that print statement for any of the AnonymousClass#, only for ones declared with `new Object()`.

**Comment by mlinarev** [comment]
Please try this to identify inner classes:

http://stackoverflow.com/questions/15699568/extract-inner-classes-using-eclipse-jdt

**Comment by eobie3** [comment]
I hit the visit TypeDeclaration statement frequently, and it's able to catch all of the nested anonymous classes. It's also catching other nested classes that I am able to hook (SettingsListClickListener, for example). When analyzing a decompiled APK, should I just exclude all nested classes found in this manner and add that as a limitation that we can't analyze nested classes in APKs?

**Comment by mlinarev** [comment]
Lets test the module generation and the data collection including all the nested classes

**Comment by eobie3** [comment]
Should I put the nested classes in try blocks?

**Comment by eobie3** [comment]
Fixed with new Xposed, which is just awesome

538be59b6867989a32716a66cbf0355de8c5588e
