### ISSUE TITLE
Decompiling CarReport produces weird class names

### ISSUE THREAD

**Issue by eobie3** [Captianrock/android_PV#51]
Decompiling the CarReport apk produces file names and packages that are just letters - a.java, b.java, etc. The module builder takes these strings literally, and xposed won't know what class we're trying to hook when that class is called "a".

**Comment by mlinarev** [comment]
Those are obfuscated classes that in most of the case belong to third party libraries. You could exclude those classes and during the parsing notify the user about the classes "excluded" from the xposed module

**Comment by eobie3** [comment]
Is there anything unique to those classes that would let us know that they are obfuscated besides their name?

**Comment by mlinarev** [comment]
No :(

**Comment by eobie3** [comment]
Would it be safe to assume that java classes start with an upper case letter? The obfuscated classes are all lower case.

**Comment by eobie3** [comment]
New Xposed creates the obfuscated class names - user will have to deal

538be59b6867989a32716a66cbf0355de8c5588e
