### ISSUE TITLE
Dynamic Updating for Traces 

### ISSUE THREAD

**Issue by Captianrock** [Captianrock/android_PV#52]
- A Bug Where traces will not update correctly

**Comment by Quansword** [comment]
My bad, thought you could assign 2 people to an issue. You can't.

**Comment by Captianrock** [comment]
-Traces are correlated to the correct button pressed. 
-Still need to dynamically update the webapp to display button correlating to the number of traces in the database. 
9bf102758b260ede327b3361797c1f88f866d7e2

**Comment by Quansword** [comment]
Added sorting options to the trace page.

See https://github.com/Captianrock/android_PV/commit/f0f413895b013d8e6b5b4844fdea471be98bd459 for more details.
