### ISSUE TITLE
Unwanted access to pages

### ISSUE THREAD

**Issue by Captianrock** [Captianrock/android_PV#60]
- If a user logs in and saves the url, then continues to log out. A user can paste the url again and gain unwanted access.

**Comment by Quansword** [comment]
Fixed in https://github.com/Captianrock/android_PV/commit/c241cda9413d3e1718761342b7d08617f2a73d6e#diff-ae477301d1c65a636b5575cb773c369c. Works well after some bugfixes and iterating in subsequent commits.
