### ISSUE TITLE
Correctly receiving input (source code)

### ISSUE THREAD

**Issue by Captianrock** [Captianrock/android_PV#7]
-Have Java program correctly reading in source code through file path
-Upload source code of open-source application (pref. default)

**Comment by Captianrock** [comment]
-Correctly recieving input. Yet to test full functionality of parser.

**Comment by Captianrock** [comment]
-Source code uploaded. Now to just test.

**Comment by eobie3** [comment]
Parser has been tested with the source code of AlarmKlock app
