### ISSUE TITLE
Add package selection page

### ISSUE THREAD

**Issue by Quansword** [Captianrock/android_PV#82]
Add a page after selecting a trace that allows the user to select what traces they want to view.

**Comment by Quansword** [comment]
Added rudimentary page and checkbox examples, and integrated page with rest of webapp. Package selection to be added soon.

See commits https://github.com/Captianrock/android_PV/commit/3f4f6a30fcd69b0a6b025fa4933272131c380d2e, https://github.com/Captianrock/android_PV/commit/df569f5649add8038f56ad046e1e6fe530dd0129, and https://github.com/Captianrock/android_PV/commit/e92cfe6546e6e31849f57f8c2df3ea06ce02c5e7.

**Comment by Captianrock** [comment]
Finished backend implementation package selection. Users can now choose all/none of the packages given and the data will be unique to those selected. 

2215478db487ef3472678534dfc314f74e347cd3
6e46a8f0fdcc5120cfde74528d297400eb03960d
