### ISSUE TITLE
Delete traces

### ISSUE THREAD

**Issue by eobie3** [Captianrock/android_PV#87]
Delete traces on website - just delete from database

**Comment by Captianrock** [comment]
- Added and formated buttons 
22b509740fa8d6f42003794d52ba0db7bd353cdf

**Comment by Quansword** [comment]
Rejiggered the trace sorting to help.

**Comment by Captianrock** [comment]
Deleting Traces implemented with Dynamic Updates to the website using AJAX calls. 
b5f029a4702761ae42db3682cd331d97ff4bd129
